### ISSUE TITLE
R is not a function

### ISSUE THREAD

**Issue by NJseo** [gburtini/Dont-Bounce-Please#25]
Wow, so everything worked until I installed on clients site, then I keep getting R is not a function. What could be happening here?

**Comment by NJseo** [comment]
It was the first time I got this error, but I cannot remember what the resolve was.

**Comment by gburtini** [comment]
Hi, without more information I'm not sure if I can help you, but check to make sure you've only included jQuery once. If that doesn't fix it, look to see where that error originates, is it in the DBP.js or a conflict with something else on the site?

This library probably needs to be updated for compatibility with other dependencies, so there may be a conflict there. I'll merge a pull request that fixes any of those sorts of conflicts.
